spring:
    devtools:
      restart:
        enabled: false
      livereload:
        enabled: false
    data:
      mongodb:
        uri: mongodb://root:root@store-mongodb:27017/store?authSource=admin&authMechanism=SCRAM-SHA-1